apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zu7x31d6c-go 
  janus-idp.io/tekton: zu7x31d6c-go
  backstage.io/kubernetes-id: zu7x31d6c-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zu7x31d6c-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml